**Importing Libraries**

In [ ]:
from tensorflow import keras
from keras.layers import Embedding, SimpleRNN,Dense
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical
from keras.models import Sequential
from keras.preprocessing.sequence import pad_sequences
from numpy import array
import numpy

**Probability calculation function**

In [ ]:
def prob(model,tok,sentence):
    print("Input Sentence is: ",sentence)
    encoded=tok.texts_to_sequences([sentence])[0]
    encoded.insert(0,0)
    encoded=array(encoded)
    encoded=numpy.reshape(encoded,newshape=(1,-1))
    print("encoded: ",encoded,encoded.shape)
    prob=model.predict_proba(encoded,verbose=0)
    #print("Prob: ",prob.shape) #(1,words,23)
    probability=1
    for i in range(prob.shape[1]-1):
        probability=probability*prob[0,i,encoded[0,i+1]]
    print("Probability of sentence is : ",probability)


**Preparing Data**

In [ ]:
data=['Jack and Jill went up the hill .','To fetch a pail of water .','Jack fell down and broke his crown .',
      'And Jill came tumbling after .']

tok= Tokenizer(filters='~`!@#$%^&*()-_+={}[]:;<\>/?|,')

tok.fit_on_texts(data)# learns the vocab
print("Word indices: ",tok.word_index)

vocab_size= len(tok.word_index)+1
print('Vocab Size is: ',vocab_size)

Num_sequences= tok.texts_to_sequences(data)
print("Sequences: ",Num_sequences,len(Num_sequences))

X=[]
Y=[]
for i in range(len(Num_sequences)):
    X.insert(i,Num_sequences[i][:-1])
    Y.insert(i,Num_sequences[i])

maxl=max([len(i) for i in X])

X=pad_sequences(X,maxlen=maxl+1,padding='pre')
print("After padding X: {}\n ".format(X))
Y=pad_sequences(Y,maxlen=maxl+1,padding='pre')
print("After padding Y: {}\n".format(Y))

Y=to_categorical(Y,num_classes=vocab_size)

print("X=",X,"\nY=",Y,X.shape,Y.shape)


Word indices:  {'.': 1, 'and': 2, 'jack': 3, 'jill': 4, 'went': 5, 'up': 6, 'the': 7, 'hill': 8, 'to': 9, 'fetch': 10, 'a': 11, 'pail': 12, 'of': 13, 'water': 14, 'fell': 15, 'down': 16, 'broke': 17, 'his': 18, 'crown': 19, 'came': 20, 'tumbling': 21, 'after': 22}
Vocab Size is:  23
Sequences:  [[3, 2, 4, 5, 6, 7, 8, 1], [9, 10, 11, 12, 13, 14, 1], [3, 15, 16, 2, 17, 18, 19, 1], [2, 4, 20, 21, 22, 1]] 4
After padding X: [[ 0  3  2  4  5  6  7  8]
 [ 0  0  9 10 11 12 13 14]
 [ 0  3 15 16  2 17 18 19]
 [ 0  0  0  2  4 20 21 22]]
 
After padding Y: [[ 3  2  4  5  6  7  8  1]
 [ 0  9 10 11 12 13 14  1]
 [ 3 15 16  2 17 18 19  1]
 [ 0  0  2  4 20 21 22  1]]

X= [[ 0  3  2  4  5  6  7  8]
 [ 0  0  9 10 11 12 13 14]
 [ 0  3 15 16  2 17 18 19]
 [ 0  0  0  2  4 20 21 22]] 
Y= [[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [

**Sequential Model**

In [ ]:
model=Sequential()
model.add(Embedding(input_dim=vocab_size,output_dim=10))
model.add(SimpleRNN(units=50, return_sequences=True))# 50 hidden neurons
model.add(Dense(units=vocab_size,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='rmsprop',metrics=['accuracy'])
model.fit(X,Y,epochs=250,verbose=1)


Epoch 1/250
1/1 [==============================] - 1s 1s/step - loss: 3.1208 - accuracy: 0.1250
Epoch 2/250
1/1 [==============================] - 0s 11ms/step - loss: 3.0888 - accuracy: 0.1875
Epoch 3/250
1/1 [==============================] - 0s 7ms/step - loss: 3.0604 - accuracy: 0.2188
Epoch 4/250
1/1 [==============================] - 0s 9ms/step - loss: 3.0290 - accuracy: 0.2500
Epoch 5/250
1/1 [==============================] - 0s 6ms/step - loss: 2.9928 - accuracy: 0.1875
Epoch 6/250
1/1 [==============================] - 0s 9ms/step - loss: 2.9516 - accuracy: 0.1250
Epoch 7/250
1/1 [==============================] - 0s 7ms/step - loss: 2.9069 - accuracy: 0.1250
Epoch 8/250
1/1 [==============================] - 0s 7ms/step - loss: 2.8607 - accuracy: 0.1250
Epoch 9/250
1/1 [==============================] - 0s 8ms/step - loss: 2.8146 - accuracy: 0.1250
Epoch 10/250
1/1 [==============================] - 0s 7ms/step - loss: 2.7689 - accuracy: 0.1250
Epoch 11/250
1/1 [===========

**Language Modelling**

In [ ]:
s=input("Enter the sentence to find the probabilty: ")
prob(model,tok,s)

Enter the sentence to find the probabilty: Jack and Jill pail water
Input Sentence is:  Jack and Jill pail water
encoded:  [[ 0  3  2  4 12 14]] (1, 6)
Probability of sentence is :  3.2488325494969366e-10


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:425: UserWarning: `model.predict_proba()` is deprecated and will be removed after 2021-01-01. Please use `model.predict()` instead.
  warnings.warn('`model.predict_proba()` is deprecated and '


**Sentence Generation**

In [ ]:
def generation(n_words):
    encoded=[]
    in_text=''

    for i in range(n_words):
        print("Intext at starting:",in_text)
        encoded=tok.texts_to_sequences([in_text])[0]
        encoded.insert(0,0)
        encoded=array(encoded)
        encoded=numpy.reshape(encoded,newshape=(1,-1))
        print("Encoded: ",encoded, encoded.shape)

        if i==0:
            prob=model.predict_proba(encoded,verbose=0)
            yhat=0
            while yhat== 0:
                yhat=numpy.argmax(prob)
            yhat=[yhat]
            yhat=array(yhat)
            yhat=numpy.reshape(yhat,(1,-1))
        else:
            prob = model.predict_proba(encoded)
            yhat = numpy.append(yhat,0)
            yhat = numpy.reshape(yhat, newshape=(1, -1))
            while yhat[0,i]==0:
                yhat[0,i]=numpy.argmax(prob[0,i])

        print("yhat: ", yhat)

        out_word=''
        for word,index in tok.word_index.items():
            if index==yhat[0,i]:
                out_word=word
                break

        in_text=in_text+' '+out_word
    return in_text


l=int(input("Enter the length of sentence that you want: "))
s=generation(l)
print('Sentence on sampling is: ',s)

Enter the length of sentence that you want: 5
Intext at starting: 
Encoded:  [[0]] (1, 1)
yhat:  [[3]]
Intext at starting:  jack
Encoded:  [[0 3]] (1, 2)
yhat:  [[ 3 15]]
Intext at starting:  jack fell
Encoded:  [[ 0  3 15]] (1, 3)
yhat:  [[ 3 15 16]]
Intext at starting:  jack fell down
Encoded:  [[ 0  3 15 16]] (1, 4)
yhat:  [[ 3 15 16  2]]
Intext at starting:  jack fell down and
Encoded:  [[ 0  3 15 16  2]] (1, 5)


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:425: UserWarning: `model.predict_proba()` is deprecated and will be removed after 2021-01-01. Please use `model.predict()` instead.
  warnings.warn('`model.predict_proba()` is deprecated and '


yhat:  [[ 3 15 16  2 17]]
Sentence on sampling is:   jack fell down and broke


**Sentence Sampling**

In [ ]:
def sample_without_seed_sampling(n_words):
    encoded=[]
    in_text=''

    for i in range(n_words):
        print("Intext at starting:",in_text)
        encoded=tok.texts_to_sequences([in_text])[0]
        encoded.insert(0,0)
        encoded=array(encoded)
        encoded=numpy.reshape(encoded,newshape=(1,-1))
        print("Encoded: ",encoded, encoded.shape)

        if i==0:
            prob=model.predict_proba(encoded,verbose=0)
            yhat=0
            while yhat== 0:
                yhat=numpy.random.choice(range(vocab_size),p=prob.ravel())
            yhat=[yhat]
            yhat=array(yhat)
            yhat=numpy.reshape(yhat,(1,-1))
        else:
            prob = model.predict_proba(encoded)
            yhat = numpy.append(yhat,0)
            yhat = numpy.reshape(yhat, newshape=(1, -1))
            while yhat[0,i]==0:
                yhat[0,i]=numpy.random.choice(range(vocab_size),p=prob[0,i].ravel())

        print("yhat: ", yhat)

        out_word=''
        for word,index in tok.word_index.items():
            if index==yhat[0,i]:
                out_word=word
                break

        in_text=in_text+' '+out_word
    return in_text

l=int(input("Enter the length of sentence that you want: "))
s=sample_without_seed_sampling(l)
print('Sentence is: ',s)

Enter the length of sentence that you want: 5
Intext at starting: 
Encoded:  [[0]] (1, 1)
yhat:  [[3]]
Intext at starting:  jack
Encoded:  [[0 3]] (1, 2)
yhat:  [[3 2]]
Intext at starting:  jack and
Encoded:  [[0 3 2]] (1, 3)
yhat:  [[3 2 4]]
Intext at starting:  jack and jill
Encoded:  [[0 3 2 4]] (1, 4)
yhat:  [[3 2 4 5]]
Intext at starting:  jack and jill went
Encoded:  [[0 3 2 4 5]] (1, 5)


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:425: UserWarning: `model.predict_proba()` is deprecated and will be removed after 2021-01-01. Please use `model.predict()` instead.
  warnings.warn('`model.predict_proba()` is deprecated and '


yhat:  [[3 2 4 5 6]]
Sentence is:   jack and jill went up
